name: Create Draft Release

on:
  push:
    tags:
      - 'v*.*.*'  # matches v1.0.0, v0.9.1, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
