name: Terraform + Deploy to EC2

on:
  push:
    branches: 
      - main
      - develop
      - add-infara-and-deploy
      - task_3-2-6_implementation
      - task_3-2-7_implementation

env:
  AWS_REGION: us-east-1
  TF_VAR_hosted_zone_id: ${{ secrets.TF_VAR_HOSTED_ZONE_ID }}
  TF_VAR_ec2_public_ip: ${{ secrets.EC2_PUBLIC_IP }}

jobs:
  terraform:
    name: Provision EC2 with Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Set REDIS_HOST from Terraform output
        run: |
          RAW_OUTPUT=$(terraform output redis_endpoint | grep -Eo '([a-zA-Z0-9-]+\.)+cache\.amazonaws\.com')
          echo "Parsed REDIS_HOST=$RAW_OUTPUT"
          echo "REDIS_HOST=$RAW_OUTPUT" >> $GITHUB_ENV

      - name: Commit state to branch (not recommended for prod!)
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b tf-state
          mkdir -p infra
          cp terraform.tfstate infra/
          git add -f infra/terraform.tfstate
          git commit -m "Save Terraform state"
          git push -f https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} tf-state
    
  deploy:
    name: Deploy Ghostfolio to EC2
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Wait for EC2 to be ready
        run: |
          echo "Waiting for EC2 to accept SSH..."
          for i in {1..15}; do
            ssh -i id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=5 ubuntu@$EC2_HOST 'echo connected' && break
            echo "Retrying in 10 seconds..."
            sleep 10
          done

      - name: Upload and run deployment script
        run: |
          scp -i id_rsa -o StrictHostKeyChecking=no deploy-ghostfolio.sh ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
          ssh -i id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'bash /home/ubuntu/deploy-ghostfolio.sh'
